# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92cf498d3f7eff023c3b5ee3d17c838349b11b9756ab24106fca572c87c8f8fa1deaadb10c17cd1e5b7f5eafb178c1d219609fef8550f880918caf1bf83fe7a3

test:
  secret_key_base: a0a53e3995cbfcb19db44d11e7c283057e9b39351c7a9c980ee84ed938a46a63692fe3c6666595ae10d5180e2d3c7a01882e3de38e2b2b298db988503d0a1de6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
